name: NPM Publish

on:
  push:
    tags:
      - "v*"

jobs:
  node:
    name: Publish to NPM
    runs-on: ubuntu-latest
    # Only runs on tags that matches the make-release action
    if: startsWith(github.ref, 'refs/tags/v')
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FSQL_PUBLISH_TOKEN }}
        run: |
          npm publish --access public
